/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Condominium } from "./Condominium";
export * as factories from "./factories";
export { Condominium__factory } from "./factories/Condominium__factory";
